name: llms
description: "A flutter binding for llama.cpp, which use platform channel."
version: 0.0.1
publish_to: 'none'
repository: https://github.com/m9m9ra/llms
issue_tracker: https://github.com/m9m9ra/llms/issues
homepage: https://pub.dev/packages/llms

platforms:
  android:
  ios:

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.m9m9ra.llms
        pluginClass: LlmsPlugin
      ios:
        pluginClass: LlmsPlugin